import { useState } from "react";
import { Download, Lock } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PaywallModal } from "@/components/PaywallModal";
import { useUsage } from "@/hooks/useUsage";
import { ExportPreset, Job } from "@/types/job";
import { ALL_COLUMNS, EXPORT_PRESETS } from "@/lib/columns";

interface ExportPanelProps {
  jobs: Job[];
}

export function ExportPanel({ jobs }: ExportPanelProps) {
  const [preset, setPreset] = useState<ExportPreset>("quick");
  const [paywallOpen, setPaywallOpen] = useState(false);
  const { canExport, trackEvent, limits } = useUsage();

  const handleExport = async () => {
    if (!canExport(preset)) {
      setPaywallOpen(true);
      return;
    }

    const columnKeys = EXPORT_PRESETS[preset] || EXPORT_PRESETS.quick;
    const columns = columnKeys
      .map((k) => ALL_COLUMNS.find((c) => c.key === k))
      .filter(Boolean);

    const headers = columns.map((c) => c!.label);

    const rows = jobs.map((j) =>
      columns
        .map((c) => {
          const val = c!.getValue(j);
          return `"${val.replace(/"/g, '""')}"`;
        })
        .join(",")
    );

    // Free plan watermark
    if (limits.plan === "free") {
      rows.push(`"Generated by Job Intelligence — Upgrade for full export",${columns.slice(1).map(() => '""').join(",")}`);
    }

    const csvContent = [headers.join(","), ...rows].join("\n");
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `job-intelligence-${preset}-${new Date().toISOString().split("T")[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);

    await trackEvent("export");
  };

  const colCount = (EXPORT_PRESETS[preset] || []).length;
  const locked = !canExport(preset);

  return (
    <>
      <div className="flex items-center gap-2">
        <Select value={preset} onValueChange={(v) => setPreset(v as ExportPreset)}>
          <SelectTrigger className="h-8 text-xs w-[160px] bg-card border-border">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="quick">Quick Overview</SelectItem>
            <SelectItem value="detailed">
              Detailed (A–K) {limits.plan === "free" && "🔒"}
            </SelectItem>
            <SelectItem value="full">
              Full + Raw Text {limits.plan === "free" && "🔒"}
            </SelectItem>
            <SelectItem value="visa">
              Visa Focus {limits.plan === "free" && "🔒"}
            </SelectItem>
            <SelectItem value="skill-gap">
              Skill Gap Focus {limits.plan === "free" && "🔒"}
            </SelectItem>
          </SelectContent>
        </Select>
        <Button size="sm" variant="outline" onClick={handleExport} className="h-8 text-xs gap-1.5">
          {locked ? <Lock className="h-3.5 w-3.5" /> : <Download className="h-3.5 w-3.5" />}
          Export ({colCount} cols)
        </Button>
      </div>

      <PaywallModal
        open={paywallOpen}
        onOpenChange={setPaywallOpen}
        feature="Full export presets"
        currentUsage="Free plan only includes Quick Overview export"
      />
    </>
  );
}
