
-- Add new columns to cached_jobs for full unified schema
ALTER TABLE public.cached_jobs
  ADD COLUMN IF NOT EXISTS source_job_id text,
  ADD COLUMN IF NOT EXISTS date_scraped timestamptz DEFAULT now(),
  ADD COLUMN IF NOT EXISTS job_status text DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS job_title_normalized text,
  ADD COLUMN IF NOT EXISTS contract_type text,
  ADD COLUMN IF NOT EXISTS remote_region text,
  ADD COLUMN IF NOT EXISTS hours_per_week_min integer,
  ADD COLUMN IF NOT EXISTS hours_per_week_max integer,
  ADD COLUMN IF NOT EXISTS department text,
  ADD COLUMN IF NOT EXISTS region_province text,
  ADD COLUMN IF NOT EXISTS postal_code text,
  ADD COLUMN IF NOT EXISTS work_address_raw text,
  ADD COLUMN IF NOT EXISTS work_lat double precision,
  ADD COLUMN IF NOT EXISTS work_lng double precision,
  ADD COLUMN IF NOT EXISTS commute_mode text,
  ADD COLUMN IF NOT EXISTS commute_distance_km double precision,
  ADD COLUMN IF NOT EXISTS commute_time_min integer,
  ADD COLUMN IF NOT EXISTS commute_time_text text,
  ADD COLUMN IF NOT EXISTS company_name_normalized text,
  ADD COLUMN IF NOT EXISTS company_website text,
  ADD COLUMN IF NOT EXISTS company_linkedin_url text,
  ADD COLUMN IF NOT EXISTS company_size text,
  ADD COLUMN IF NOT EXISTS company_type text,
  ADD COLUMN IF NOT EXISTS salary_period text,
  ADD COLUMN IF NOT EXISTS salary_text_raw text,
  ADD COLUMN IF NOT EXISTS bonus_mentioned text DEFAULT 'no',
  ADD COLUMN IF NOT EXISTS equity_mentioned text DEFAULT 'no',
  ADD COLUMN IF NOT EXISTS job_description_language text,
  ADD COLUMN IF NOT EXISTS language_level text,
  ADD COLUMN IF NOT EXISTS relocation_support_mentioned text DEFAULT 'no',
  ADD COLUMN IF NOT EXISTS degree_fields text[],
  ADD COLUMN IF NOT EXISTS certifications text[],
  ADD COLUMN IF NOT EXISTS cloud_platforms text[],
  ADD COLUMN IF NOT EXISTS ml_ds_methods text[],
  ADD COLUMN IF NOT EXISTS data_stack text[],
  ADD COLUMN IF NOT EXISTS nice_to_have_skills text[],
  ADD COLUMN IF NOT EXISTS pension text DEFAULT 'no',
  ADD COLUMN IF NOT EXISTS health_insurance text DEFAULT 'no',
  ADD COLUMN IF NOT EXISTS learning_budget text DEFAULT 'no',
  ADD COLUMN IF NOT EXISTS learning_budget_amount text,
  ADD COLUMN IF NOT EXISTS transport_allowance text DEFAULT 'no',
  ADD COLUMN IF NOT EXISTS car_lease text DEFAULT 'no',
  ADD COLUMN IF NOT EXISTS home_office_budget text DEFAULT 'no',
  ADD COLUMN IF NOT EXISTS gym_wellbeing text DEFAULT 'no',
  ADD COLUMN IF NOT EXISTS extra_holidays text DEFAULT 'no',
  ADD COLUMN IF NOT EXISTS parental_leave text DEFAULT 'no',
  ADD COLUMN IF NOT EXISTS benefits_text_raw text,
  ADD COLUMN IF NOT EXISTS requirements_raw text,
  ADD COLUMN IF NOT EXISTS company_description_raw text;
